### PR TITLE
Use png_get_xxx() calls instead of accessing the struct png_info

### PR DESCRIPTION
**Pull request by mkrzysztofowicz**
As per the portability note in the libpng documentation, direct access to the
png_info and png_struct has been deprecated and as of libpng 1.5 those structs
are no longer in the public headers. Various png_get_xxx() and png_set_xxx()
accessor functions have been available from almost the time libpng existed
itself, therefore the above change should be backwards compatible.

If you're using libpng 1.5 or newer (at the time of this modification, CentOS
7 comes with libpng 1.5.13), you will be affected by this change in libpng
compared to version 1.4 or older. This commit addresses this issue.

### CODE REVIEW

**Comment by ksterne** [comment]
Hello @mkrzysztofowicz,


Sorry it's taken me a while to get around to this.  Finally coming up from under a lot of work...just in time to go on another trip in a little over a week.  

Looking at this, do you have a good simple test that I could run here to test out the fix?  I'm not familiar with the libpng library or making calls to it, so it would be good to see the current develop branch break and the fix in your branch.

**Comment by mkrzysztofowicz** [comment]
Hi @ksterne,

This time it took me a good while to reply to you - sorry about that. I've been away myself for most of November and have been traveling South in December, and finally I'm now catching up on stuff. 

I don't actually have a test per se. The code before the changes simply wouldn't compile on CentOS 7 or indeed on any system with libpng 1.5 or newer, while after the change it did. 

We really only use make_fit and make_smr tools for processing the SuperDARN data and use our own IDL code for plotting (which as far as I know predates the plotting tools bundled with the RST). I did try the time_plot and it produces plots, but our workflow is not using the built-in time_plot tool.

**Comment by kkotyk** [comment]
Can I merge this? Mike is correct in that you cant install RST if your system uses a higher version of libpng.

**Comment by pasha-ponomarenko** [comment]
Yep, if it fixes the problem then go for it.

Cheers,
Pasha

Sent from my Sony Xperia™ smartphone


---- kkotyk wrote ----


Can I merge this? Mike is correct in that you cant install RST if your system uses a higher version of libpng.

**Pull request merged**
